language: node_js
node_js:
  - 0.11
  - 0.12
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install imagemagick libmagickwand-dev libmagickcore-dev libgif-dev
  - npm install
  - node app.js devide_by_2.10cs.11x4.png
  - mv tests/gcd.js tests.js
  - node app.js tests/gcd.png
  - mv tests/swap.js tests.js
  - node app.js tests/swap.png
  - sed -i -e "s/var codel = 10;/var codel = 1;/" config.js
  - mv tests/lisp-like-calc.js tests.js
  - node app.js tests/lisp-like-calc.png
